### ISSUE TITLE
throw Not Implemented errors for todos

### ISSUE THREAD

**Issue by ImLunaHey** [demonsters/prisma-mock#17]
When using this I noticed I was getting a confusing error, `TypeError: Cannot read properties of undefined (reading 'then')` which I'm guessing is because I was calling `.then` on `.aggregate` which isn't done yet.

Instead of that error it'd be nice if we could get a `Not Implemented` error thrown so we'd at least know that's the reason for it not working.

**Comment by stijnvanderlaan** [comment]
Added warnings for $use, aggregate & groupBy in version 0.4.0
