### ISSUE TITLE
"jest is not defined"

### ISSUE THREAD

**Issue by LocatedInSpace** [demonsters/prisma-mock#25]
Upon adding the below (I followed the example) - I run into the following error
![billede](https://user-images.githubusercontent.com/48300341/224353067-370eba09-1d08-4007-aa0c-ca64a3a1143d.png)
I've tried adding the following to resolve jest
```
import {jest} from '@jest/globals'
global.jest = jest;
```
However, it just results in the following error 
![billede](https://user-images.githubusercontent.com/48300341/224353753-e95f3931-df88-4c12-83ae-003d38ae58ba.png)

I obviously must be doing something wrong - but I am unable to see what, could you help shed some light on my misunderstanding?

**Comment by stijnvanderlaan** [comment]
Hi @LocatedInSpace, thanks for your feedback. In what environment are you trying prisma-mock? In jest, vitest or somewhere als?

**Comment by LocatedInSpace** [comment]
I've tried primarily with vitest, and secondhand with jest - I now however see this (https://github.com/demonsters/prisma-mock/issues/20), so I assume vitest isn't supported atm, and was a stupid thing to try 😥 

I'm going to assume that this was an issue with how I've configured jest then - please close the issue, and I'll reopen with better details if it persists once I've properly tested with jest :)
