### ISSUE TITLE
$transaction does not return a value for interactive transactions

### ISSUE THREAD

**Issue by dilsher1** [demonsters/prisma-mock#42]
First of all, thanks for this amazing library.

One issue I've noticed is that $transaction doesn't return a value for interactive transactions. I believe this could likely be remedied by just adding a return statement to line 186 to return the results of await actions(client) call.

https://github.com/demonsters/prisma-mock/blob/main/src/index.ts#L186

See the pull request for this issue here:
https://github.com/demonsters/prisma-mock/pull/43

**Comment by stijnvanderlaan** [comment]
Thanks @dilsher1
