### ISSUE TITLE
Interactive transactions don't return errors if the promise fails

### ISSUE THREAD

**Issue by dilsher1** [demonsters/prisma-mock#44]
Currently if an interactive transaction is run and the Promise throws an exception then the behavior in Prisma is for the $transaction function to throw this error. The current behavior ends up catching this error and not returning this error which causes an inconsistency for tests where you intend transactions to fail.

See https://github.com/demonsters/prisma-mock/pull/45

**Comment by stijnvanderlaan** [comment]
Fixed in v0.10.0
