### ISSUE TITLE
AutoIncrement doesn't support BigInt

### ISSUE THREAD

**Issue by dilsher1** [demonsters/prisma-mock#54]
Realized I forgot to file a specific ticket for this. Currently the typing for autoincrement assumes it will be a number since it makes use of Math functions which require Numbers. I've proposed a fix at: https://github.com/demonsters/prisma-mock/pull/52

**Comment by jcbdev** [comment]
I could really do with this update 🙏

**Comment by stijnvanderlaan** [comment]
Merged & released in v0.10.1

**Comment by jcbdev** [comment]
works great. thanks
