### ISSUE TITLE
Filtering a json value with `equals` doesn't work

### ISSUE THREAD

**Issue by leighman** [demonsters/prisma-mock#7]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-exact-field-value
Prisma supports querying a json value with `equals`.
Since it looks like the mock just stores objects, two objects will not compare equal with `===`.
Maybe the filter needs to use deep equals?
Great project. Thanks.

**Comment by stijnvanderlaan** [comment]
Fixed this in version 0.2.0

**Comment by leighman** [comment]
Nice one. Thanks.
